### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by ghost** [disnet/contracts.coffee#20]
I have an app I want to introduce fewer coding related bugs and it seems that this library could help me with it.

Here are some questions I need to know before I implement it in my code:
1. Is it considered production ready?
2. Should contacts be used everywhere or only in critical parts since it introduces a performance load?
3. Would it be better to use it only in tests and strip it out from the production code thus preventing bugs while prohibiting performance to be affected?
4. Does it work for all browsers, even those without proxy support?
5. Is the goal to introduce it in CoffeeScript?

**Comment by disnet** [comment]
> Is it considered production ready?

That's kinda subjective and depends on what you mean by production ready :) 

Hopefully my other answers can help you decide that.

> Should contacts be used everywhere or only in critical parts since it introduces a performance load?

I've found the most useful place to put them is on module boundaries. It helps to clarify and verify the interacting components in your code.

I'll also put them on specific functions inside a module when trying to track down a particular bug.

> Would it be better to use it only in tests and strip it out from the production code thus preventing bugs while prohibiting performance to be affected?

That's probably the best idea. But it depends on the performance of your code. As long as the performance cost of contracts in your app isn't noticeable it might make sense to leave them turned on in production (though if you need to support browsers that don't have proxies yet you'll need to leave them turned off).

> Does it work for all browsers, even those without proxy support?

Nope. Or rather, it will work in browsers without proxies as long as you compile without contract support (leaving off the `-C` flag). So your code can still have the contract annotations in CoffeeScript but they won't actually do any checking in the generated JavaScript.

> Is the goal to introduce it in CoffeeScript?

No. One of the goals of CoffeeScript is to keep it as close to a one-to-one mapping to JavaScript as possible and contracts mess that up due to the required library. I intend to keep contracts.coffee a proper superset of CoffeeScript through, so if you ever need to move back to the vanilla CoffeeScript compiler just delete of the contract annotations in your code and it should all just work.

FYI, it's probably better to talk about stuff like this over on the discussion group: https://groups.google.com/forum/?hl=en#!forum/contractscoffee

**Comment by ghost** [comment]
Okay, sounds like I can use it for Chrome in development and then compile it without support for production.

Ah, didn't know there was a discussion group, sweet, I'll post my questions there in the future!
