### ISSUE TITLE
Use comment tags instead?

### ISSUE THREAD

**Issue by ghost** [disnet/contracts.coffee#22]
After having had a lot of problems making this to work I wonder if it's a better idea to use it as comment tags instead?

Eg.

```
# @param {String} firstName First name of the user
# @param {String} lastName Last name of the user
# @param {Number} age Age of the user
# @returns {Object}
#   {String} name Full name of the user
#   {Boolean} isOld Whether the user is old or not
createUser: (firstName, lastName, age) ->
  {fullName: "#{firstName} #{lastName}", isOld: if age > 18 then yes else no}
```

Benefits:
- Compatible with CoffeeScript (thus Browserify). If you have thousands of assertions you don't want to remove them or comment them out manually, just to reverse them again when you need them. It won't do in practice.
- Compatible with http://code.google.com/p/jsdoc-toolkit/wiki/TagReference. No need to change anything if you already have comments in this style.
- The same for JS and Coffee source.
- Have it in one place (with the other tags and descriptions). No need to have them in different places.
- Convention. _The way_ to do it, not a custom way of some framework.
- Makes people like to comment their source!
- The JS way, not the Haskell way.

What do you think?

**Comment by disnet** [comment]
So we actually had this come up [before](https://github.com/disnet/contracts.coffee/pull/12). Initially the reason it wouldn't work is the `.use` problem...contracts actually did more than just throw an exception when violated, they created an object with `.use` you had to first call.

Now that's been fixed we could conceivable put the contract annotations behind comments but I still don't like the idea. To my mind putting stuff in a comment signals to the programmer that nothing will be changed at runtime. Comments reflect a static notion of the code but putting contracts in comments would confuse this point. Even worse, contracts can contain arbitrary bits of code so now you would have real code behind a comment that gets executed.

Keeping contracts as code helps signal that contracts are on the same level as the rest of the code. That's my design feel about this anyway.

**Comment by ghost** [comment]
Fair enough then, I'll check back later when the proxy support is there for every browser!

**Comment by ghost** [comment]
I'll closed this issue some days ago but I thought about something I wanna add to the discussion:
1. Using the current method the editor doesn't recognize :: as CS code and gives a syntax error. I doubt any editor will implement another syntax based on a library.
2. Since it's not CS code I can't use "coffee" to compile the source code. Hosting services are already slow to adapt CoffeeScript, but they are getting there. I doubt they will use Contracts to compile the source. Having to compile it manually when it has worked on the fly before is a step backwards.

A product for me is about features, but it's also about having the right "go to market" strategy. It seems that with the current approach many people will find it struggling to implement it for real development/production. It's restricting it's potential to reach out to everyone.

I'm not aware of the feature to run custom logic. But I feel that reaching out to the mass while staying compatible with everything without modification is an appealing feature, perhaps even more than running custom logic. Perhaps there is another way to do the custom logic thing while staying CS compatible?

I still think this method is a real time/compatibility saver and will make it from fitting a small user base, to fitting basically every JS/CS coder.

I'll have it opened til I know this feature is a 100% no go.

**Comment by disnet** [comment]
> Using the current method the editor doesn't recognize :: as CS code and gives a syntax error. I doubt any editor will implement another syntax based on a library.

True, but contracts.coffee is a language not a library. Also, for most editors this is straightforward to fix, just modify the syntax files. I haven't done this yet since it hasn't bother me too much. Which editor are you using?

> Hosting services are already slow to adapt CoffeeScript, but they are getting there.

Why do hosting services matter? Don't you compile CoffeeScript locally anyway and upload the JS? Not convinced there's much benefit here.

> I still think this method is a real time/compatibility saver and will make it from fitting a small user base, to fitting basically every JS/CS coder.

I appreciate the enthusiasm but I think the more limiting factor is Proxy support. 

Here's my fundamental thinking: contracts.coffee is an experiment in language design to provide an expressive syntax for contracts. Putting contracts in comments decreases that expressiveness for what seems to me too little benefit.

If people are interested in using contracts in their CS/JS code but still want the ability to use the standard CS compiler they can always just directly use the underlying [contracts.js](https://github.com/disnet/contracts.js) library. The syntax isn't even that bad in CS:

```
id = guard([Num], Num, 
    (x) -> x)
```

> I'll have it opened til I know this feature is a 100% no go.

Sorry, but it's a no go for contracts.coffee. 

Feel free to run with [x1024](https://github.com/disnet/contracts.coffee/pull/12)'s fork though! Or you could try the javadoc style (though I think you'll run into some expression problems with more interesting contracts: higher-order, dependent, object invariant, etc.).
